export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  jobType: 'full-time' | 'part-time' | 'contract';
  salary?: string;
  languages: string[];
  description: string;
  requirements: string[];
  postedDate: string;
  expiryDate: string;
  logo?: string;
}

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Operations Coordinator – European Events',
    company: 'Europe Congress',
    location: 'Prague',
    jobType: 'full-time',
    languages: ['English'],
    description: 'Shape Unforgettable Experiences Across Europe. Join our dynamic team to coordinate and execute high-profile European events.',
    requirements: ['Fluent English', 'Event management experience', 'Strong organizational skills'],
    postedDate: '2024-08-15',
    expiryDate: '2024-09-15',
  },
  {
    id: '2',
    title: 'High School Computer Science Teacher',
    company: 'ACGA',
    location: 'Prague',
    jobType: 'part-time',
    languages: ['English', 'Czech'],
    description: 'Teach IT at a private gymnazium in the center of Prague! Perfect opportunity for tech professionals.',
    requirements: ['Teaching qualification', 'Computer Science background', 'English and Czech fluency'],
    postedDate: '2024-08-14',
    expiryDate: '2024-09-14',
  },
  {
    id: '3',
    title: 'High School Spanish Teacher',
    company: 'ACGA',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 40,000 - 50,000',
    languages: ['English', 'Spanish'],
    description: 'Profesor/a de español en centro de educación secundaria. Join our international school environment.',
    requirements: ['Native Spanish speaker', 'Teaching certification', 'English proficiency'],
    postedDate: '2024-08-13',
    expiryDate: '2024-09-13',
  },
  {
    id: '4',
    title: 'Assistance Coordinator (French & Ukrainian)',
    company: 'Euro-Center Prague, s.r.o.',
    location: 'Prague',
    jobType: 'full-time',
    languages: ['English', 'French', 'Ukrainian'],
    description: 'Trusted medical assistance making global travel safer and stress-free. Coordinate emergency medical services.',
    requirements: ['French and Ukrainian fluency', 'Customer service experience', 'Medical terminology knowledge'],
    postedDate: '2024-08-12',
    expiryDate: '2024-09-12',
  },
  {
    id: '5',
    title: 'Assistance Coordinator (French & Bulgarian)',
    company: 'Euro-Center Prague, s.r.o.',
    location: 'Prague',
    jobType: 'full-time',
    languages: ['English', 'French', 'Bulgarian'],
    description: 'Trusted medical assistance making global travel safer and stress-free. Handle multilingual support cases.',
    requirements: ['French and Bulgarian fluency', 'Emergency response experience', 'Strong communication skills'],
    postedDate: '2024-08-11',
    expiryDate: '2024-09-11',
  },
  {
    id: '6',
    title: 'Lodging Partner Associate',
    company: 'Expedia',
    location: 'Prague',
    jobType: 'full-time',
    languages: ['English', 'Danish'],
    description: 'B2B Customer service role within global travel tech leader. Work with accommodation partners worldwide.',
    requirements: ['Danish fluency', 'B2B experience', 'Travel industry knowledge preferred'],
    postedDate: '2024-08-10',
    expiryDate: '2024-09-10',
  },
  {
    id: '7',
    title: 'Customer Advisor with Finnish',
    company: 'BlueLink International CZ',
    location: 'Prague',
    jobType: 'full-time',
    languages: ['English', 'Finnish'],
    description: 'Paid training, discounted airline tickets, relocation support. Join our international customer service team.',
    requirements: ['Native Finnish speaker', 'Customer service experience', 'EU work authorization'],
    postedDate: '2024-08-09',
    expiryDate: '2024-09-09',
  },
  {
    id: '8',
    title: 'Software Engineer',
    company: 'Tech Solutions Prague',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 80,000 - 120,000',
    languages: ['English'],
    description: 'Join our growing tech team developing innovative software solutions for European markets.',
    requirements: ['3+ years experience', 'React/Node.js', 'English fluency', 'EU work permit'],
    postedDate: '2024-08-08',
    expiryDate: '2024-09-08',
  },
  {
    id: '9',
    title: 'Marketing Manager',
    company: 'Global Ventures Czech',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 60,000 - 80,000',
    languages: ['English', 'German'],
    description: 'Lead marketing initiatives across Central European markets. Drive brand awareness and customer acquisition.',
    requirements: ['Marketing degree', '5+ years experience', 'German preferred', 'Digital marketing expertise'],
    postedDate: '2024-08-07',
    expiryDate: '2024-09-07',
  },
  {
    id: '10',
    title: 'Financial Analyst',
    company: 'Investment Partners CZ',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 70,000 - 95,000',
    languages: ['English'],
    description: 'Analyze investment opportunities and provide financial insights for our growing portfolio.',
    requirements: ['Finance degree', 'Excel expertise', 'CFA preferred', 'English fluency'],
    postedDate: '2024-08-06',
    expiryDate: '2024-09-06',
  },
  {
    id: '11',
    title: 'UX/UI Designer',
    company: 'Design Studio Prague',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 65,000 - 85,000',
    languages: ['English'],
    description: 'Create intuitive user experiences for our digital products. Work with international clients.',
    requirements: ['Portfolio required', 'Figma/Sketch', '3+ years experience', 'English fluency'],
    postedDate: '2024-08-05',
    expiryDate: '2024-09-05',
  },
  {
    id: '12',
    title: 'Sales Representative',
    company: 'Business Solutions Group',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 45,000 + commission',
    languages: ['English', 'Czech'],
    description: 'Drive B2B sales for innovative business solutions. Great earning potential with commission structure.',
    requirements: ['Sales experience', 'Czech advantage', 'Driving license', 'Goal-oriented mindset'],
    postedDate: '2024-08-04',
    expiryDate: '2024-09-04',
  },
  {
    id: '13',
    title: 'Content Writer',
    company: 'Media House Prague',
    location: 'Prague',
    jobType: 'part-time',
    salary: 'CZK 25,000 - 35,000',
    languages: ['English'],
    description: 'Create engaging content for various digital platforms. Flexible working hours available.',
    requirements: ['Native English', 'Writing portfolio', 'SEO knowledge', 'Social media experience'],
    postedDate: '2024-08-03',
    expiryDate: '2024-09-03',
  },
  {
    id: '14',
    title: 'Project Manager',
    company: 'Consulting Partners',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 75,000 - 100,000',
    languages: ['English', 'German'],
    description: 'Lead cross-functional teams delivering complex consulting projects for international clients.',
    requirements: ['PMP certification preferred', '5+ years experience', 'German advantage', 'Agile methodology'],
    postedDate: '2024-08-02',
    expiryDate: '2024-09-02',
  },
  {
    id: '15',
    title: 'Data Scientist',
    company: 'Analytics Corp Prague',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 85,000 - 115,000',
    languages: ['English'],
    description: 'Analyze complex datasets and build predictive models for business intelligence solutions.',
    requirements: ['Python/R expertise', 'Machine learning', 'Statistics background', 'PhD preferred'],
    postedDate: '2024-08-01',
    expiryDate: '2024-09-01',
  },
  {
    id: '16',
    title: 'HR Specialist',
    company: 'Talent Solutions Czech',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 50,000 - 65,000',
    languages: ['English', 'Czech'],
    description: 'Support recruitment and employee development initiatives in our growing organization.',
    requirements: ['HR degree', 'Czech fluency', 'Recruitment experience', 'Employment law knowledge'],
    postedDate: '2024-07-31',
    expiryDate: '2024-08-31',
  },
  {
    id: '17',
    title: 'Graphic Designer',
    company: 'Creative Agency Prague',
    location: 'Prague',
    jobType: 'contract',
    salary: 'CZK 400/hour',
    languages: ['English'],
    description: 'Create visual designs for marketing campaigns and brand materials. Freelance opportunity.',
    requirements: ['Adobe Creative Suite', 'Brand design portfolio', 'Deadline-oriented', 'English fluency'],
    postedDate: '2024-07-30',
    expiryDate: '2024-08-30',
  },
  {
    id: '18',
    title: 'Business Analyst',
    company: 'Strategy Consultants',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 65,000 - 80,000',
    languages: ['English'],
    description: 'Analyze business processes and recommend improvements for operational efficiency.',
    requirements: ['Business degree', 'SQL knowledge', 'Process mapping', 'Analytical thinking'],
    postedDate: '2024-07-29',
    expiryDate: '2024-08-29',
  },
  {
    id: '19',
    title: 'English Teacher',
    company: 'International Language School',
    location: 'Prague',
    jobType: 'part-time',
    salary: 'CZK 400-600/lesson',
    languages: ['English'],
    description: 'Teach English to adult learners and corporate clients. Flexible schedule available.',
    requirements: ['TEFL/TESOL certification', 'Native English speaker', 'Teaching experience', 'EU work permit'],
    postedDate: '2024-07-28',
    expiryDate: '2024-08-28',
  },
  {
    id: '20',
    title: 'Account Manager',
    company: 'Client Services Prague',
    location: 'Prague',
    jobType: 'full-time',
    salary: 'CZK 55,000 - 70,000',
    languages: ['English', 'French'],
    description: 'Manage relationships with key international clients and drive business growth.',
    requirements: ['Account management experience', 'French preferred', 'CRM systems', 'Relationship building'],
    postedDate: '2024-07-27',
    expiryDate: '2024-08-27',
  },
];